Add 1.19's support and support Minecraft version without patch version (1.18, 1.19)
dscalzi/Nebula pull request #46
Opened 2022-06-24 16:07 UTC by TheoPierne

- Adding 1.19 support.
- Support Minecraft version without patch version like 1.18, 1.19 to avoiding : https://github.com/dscalzi/Nebula/blob/8c224e3e398d76a9514e0975e7bd04506c30141d/src/util/MinecraftVersion.ts#L16

2022-06-25 01:15 UTC, dscalzi commented
As I've said before, the problem is not supporting these new versions, the java handling in the main launcher has to be updated.

2022-11-02 08:47 UTC, GeekCornerGH requested changes

2022-11-02 08:47 UTC, GeekCornerGH commented on src/util/MinecraftVersion.ts
> +    public toString(): string { return this.revision === null ? `${this.major}.${this.minor}` : `${this.major}.${this.minor}.${this.revision}`}
Seems good

2022-11-02 08:47 UTC, GeekCornerGH commented on src/resolver/forge/adapter/ForgeGradle3.resolver.ts
> +        return VersionUtil.isVersionAcceptable(version, [12, 13, 14, 15, 16, 17, 18, 19])
```suggestion
        return VersionUtil.isVersionAcceptable(version, [12, 13, 14, 15, 16])
```
Adding other versions would be better in another PR

2022-11-02 08:47 UTC, GeekCornerGH commented on src/resolver/forge/adapter/ForgeGradle3.resolver.ts
> +        if(VersionUtil.isVersionAcceptable(this.minecraftVersion, [13, 14, 15, 16, 17, 18, 19])) {
```suggestion
        // Configure for 13, 14, 15, 16
        if(VersionUtil.isVersionAcceptable(this.minecraftVersion, [13, 14, 15, 16])) {
```
Here again too

2022-11-02 08:47 UTC, GeekCornerGH commented on src/structure/spec_model/module/forgemod/ForgeMod113.struct.ts
> +        return VersionUtil.isVersionAcceptable(version, [13, 14, 15, 16, 17, 18, 19])
```suggestion
        return VersionUtil.isVersionAcceptable(version, [13, 14, 15, 16])
```
Again, in a separate PR once 1.17+ has landed in Helios

2022-11-27 03:04 UTC, dscalzi commented
Thanks, will be handled by #50

2022-11-27 03:04 UTC, closed without merging